version: "3.9"
services:
  task_manager_ts:
    build: .
    container_name: task_manager_ts
    ports:
      - "5000:5000"
    depends_on:
      - task_manager_mongo_ts
      - task_manager_nginx_ts

  task_manager_mongo_ts:
    image: mongo:latest
    container_name: task_manager_mongo_ts

  task_manager_nginx_ts:
    image: nginx
    container_name: task_manager_nginx_ts
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

    restart: unless-stopped
