version: "3.9"
services:
  tast_manager_ts:
    build: .
    container_name: tast_manager_ts
    ports:
      - "3000:3000"
    depends_on:
      - mongo_ts
      - nginx_ts

  mongo_ts:
    image: mongo:latest
    container_name: mongo_ts

  nginx_ts:
    image: nginx
    container_name: nginx_ts
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

    restart: unless-stopped
